### ISSUE TITLE
[Feature request] Create the results files as you go

### ISSUE THREAD

**Issue by bontchev** [hasherezade/mal_sort#2]
When run on a large set of hashes, the script often hangs. (Don't know why, don't even know if it is its fault or VT's.) I have to kill it and all the work is lost. Would it be possible to keep the FOUND and NOTFOUND files constantly up-to-date as the script works, instead of creating them after it ends? Close and re-open them between the VT queries, if necessary - you wait for 3 seconds anyway, so speed isn't an issue.

**Comment by bontchev** [comment]
Now I am getting the bizarre error

```
Traceback (most recent call last):
  File "C:\Work\Transfer\vtscan.py", line 394, in <module>
    sys.exit(main())
  File "C:\Work\Transfer\vtscan.py", line 378, in main
    nfound_file.write("%s\n" % mhash).flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

I can probably suppress it with try/except but it's better to figure out what is causing it and to fix the problem. It happens only after a lot of requests; not immediately after running the script.

**Comment by hasherezade** [comment]
thanks for the notice. in fact it is not bizarre error, just I made a bizarre typo ;) flush should never be at the end of this line - so when it adds to 'not found file', it tries to flush a result of the write function, rather than flushing the file. now it is fixed!
